controllers:
    resource: ../src/Controller/
    type: annotation

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.php"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.php"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.php"
    prefix:   /login

google_login:
    path: /login/check-google

kernel:
    resource: ../src/Kernel.php
    type: annotation
